version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: app_nodejs
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - todo-app

  db:
    image: mongo:latest
    container_name: app_mongodb
    restart: unless-stopped

    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - todo-app

networks:
  todo-app:
    driver: "bridge"
